name: sicoin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  lottie: ^3.1.2
  video_player: ^2.8.6

  # =============================================================
  # === DEPENDENSI DATABASE ===
  sqflite: ^2.3.3+1    # Database offline (Android/iOS)
  path: ^1.9.0         # Helper path
  uuid: ^4.4.0         # Generator ID unik

  # === TAMBAHAN WAJIB UNTUK WEB AGAR TIDAK ERROR ===
  sqflite_common_ffi_web: ^0.4.4  # <--- INI KUNCI PERBAIKANNYA
  # =============================================================

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/videos/
